import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/Theme/themeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <Sidebar />
          <main className=" grid w-full h-full lg:pl-[300px] md:pl-[250px] sm:pl-[200px]">
            <Header />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
